### ISSUE TITLE
Dispatch Alerts not showing Callsign or Officer Name

### ISSUE THREAD

**Issue by mrdigital0** [Mythic-Framework/mythic-framework#25]
Callsign - First Last not showing in Dispatch Alerts see screenshot 

![Image](https://github.com/user-attachments/assets/86210de5-fb22-4146-96dc-18e447d0f8ff)

when adding a print the print does show correct info 

![Image](https://github.com/user-attachments/assets/8b5f49bd-2600-4421-81f2-4abc5d1c54aa)

Issue lies within the js code showing the alert

**Comment by Sampuke** [comment]
Fixed
