### ISSUE TITLE
problem with account

### ISSUE THREAD

**Issue by Gangstaaaaa** [Mythic-Framework/mythic-framework#7]
**Describe the bug**
when 3 or more players have played on the framework it gives the same number for account, this causes it to give someone else character the was previously made 

**To Reproduce**
1 make sure 3 people at least has been on the server
2 someone news joins already has a character someone else has made

3 when i was trying to find the error i new it was something to do with playerSrc so i saw account it was the same number
4. then i use someone else account number and i ended up with that persons already made character

**Expected behavior**
1. when reproduce the error i changed account number with someone else account number and ended up with their pre made character.

2. someone new joins and gets the same account number. 

**Screenshots**
![acc](https://github.com/Mythic-Framework/mythic-framework/assets/85770558/be397251-94fb-4320-83d5-d06aa2d95ee4)

**Client (please complete the following information):**
 - OS: [e.g. Windows 10 1809]
- Specs: [e.g. i5-8400, GTX 1070, 32GB Memory]

**Server (please complete the following information):**
 - OS [e.g. Windows Server 2019]
- Sepcs [e.g. 6 Cores, 8GB Memory, 100Mbps bandwidth)

**Additional context**
no errors with server console and fivem console

**Comment by ChrisHaywood90** [comment]
Hi. Please drop all of your collections within MongoDB and then restart the server and allow everything to rebuild.

**Comment by itzalfie01** [comment]
Have you carried out the SID fix in our discord ?
